# Generated by Django 2.2 on 2020-03-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dopacjenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pacjent', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('contact', models.CharField(blank=True, max_length=255)),
                ('date_send', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
