# Generated by Django 2.2 on 2020-03-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpk', '0002_dopacjenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pacjent',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(),
        ),
    ]
